### ISSUE TITLE
is there a way to have side by side images in the html

### ISSUE THREAD

**Issue by muttistefano** [dchaplinsky/visual-logging#13]
Hi , thanks fro the great work.
I was wondering if there is a way to generate the html having some images side by side, instead of haveing a "newline" between them. 
Thanks

**Comment by dchaplinsky** [comment]
As far as I can see from code, it doesn't add newlines/BR's explicitly:
https://github.com/dchaplinsky/visual-logging/blob/master/vlogging/__init__.py#L94

Feel free to give it a try

**Comment by muttistefano** [comment]
Hello, 
indeed there are no newlines between images.
I managed to have side by side images by zooming out the browser page.
Thanks
